### ISSUE TITLE
Side effects in Stream#write

### ISSUE THREAD

**Issue by sluukkonen** [marnusw/bunyan-bugsnag#3]
The `Stream#write` implementation deletes `err` and `error` properties from the payload, which causes problems when bunyan is used with multiple streams. Streams defined after `bunyan-bugsnag` won't see these properties.

**Comment by marnusw** [comment]
Thanks for pointing this out. I'm going to try to make time to fix it later today, but if I don't and you're up for creating a PR that would also be great.

**Comment by marnusw** [comment]
Fixed in `1.0.2`
